### ISSUE TITLE
Question -- How secure is to use this in production?

### ISSUE THREAD

**Issue by woss** [healzer/ipfs-file-encryption#2]
Hi there.

I really like the approach, it's minimal and does the job. I am wondering how secure and safe would this be to use in a production app?

Thanks

**Comment by healzer** [comment]
Hey,

Good question.
The security mechanism itself is production-level.
But the infrastructure on how you want to manage the encryption keys is up to the developer to determine.

Does that answer it?

**Comment by woss** [comment]
Perfectly!

Another thing i noticed last night when I was playing with your implementation. I made all the keys static but everytime I ran the script the CID changes on the MFS. do you have any idea why?

my fork https://github.com/woss/ipfs-file-encryption/tree/keys-static

**Comment by healzer** [comment]
Interesting, make sure the two testing functions on line 28 & 29 are not causing this issue.

**Comment by woss** [comment]
you mean in your repo?
```
ln28     Buffer.from(iv, 'utf8'),     // char length: 16
ln29     Buffer.from(ebuff, 'utf8')
```

my fork 
```
ln28 generateKeys()
ln29 _testing()
```

**Comment by woss** [comment]
why would they cause the issue? they are just creating a Buffer from the string

**Comment by healzer** [comment]
I mean in your fork.

I'm not an expert on ipfs, just verifying

**Comment by woss** [comment]
the `generateKeys` func is solid, if statements prevent the recreation of the keys. 

I've asked on the IPFS forum what's the issue,  they should know. 

have you ever considered how would this work if you would like to share the encrypted file with someone with some ACL?

I'm building a platform for photographers where they can obtain the copyrights after successfully completing a process. Your approach on encryption is a perfect fit for the platform.

if you would like to know more check the old website https://sensio.group or the Process description here https://anagolay.dev

**Comment by woss** [comment]
i think i found a culprit :) 

the issue is in the RSA signing `const encrypted = crypto.publicEncrypt(publicKey, buffer)`
As per https://stackoverflow.com/questions/66423321/node-crypto-publicencrypt-returns-different-value-each-time-it-is-used  and https://stackoverflow.com/questions/57779904/what-strategy-to-turn-non-pure-functions-into-a-pure-functions-in-javascript/57780030#57780030 

Short answer: 
```md
This is impossible when doing asymmetric encryption because a random session key is generated for each operation. The session key is encrypted with the public key, and then the session key is used to encrypt the payload. The returned value is usually just an encoded version of two values: (1) the pubkey-encrypted session key, and (2) the session key -encrypted payload.

Both of these values are going to be different each time you call the function because the session key is going to be different each time.
```

**Comment by healzer** [comment]
Ah yes I see the issue. Each time you encrypt the same file you end up with a different payload duento a unique encryption key.

I'm sure you could work around this by caching the key in your own server or something.

**Comment by woss** [comment]
nope, the thing is in this `This is impossible when doing asymmetric encryption because a random session key is generated for each operation.` even the key is cached this randomness will make the payload different. 

Now I'm thinking about the following; why RSA in the first place, sharing the file with someone else would be a pain in the ass. 

Why not just AES, that will always produce the same payload. And then we could just give the receiver the key so they can encrypt it. 

Also need to see how keybase did their encryption.

I'll close this. Otherwise, we will get sidetracked.
